version: "3"

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '3306:3306'
    env_file:
      - ./.env
